### ISSUE TITLE
ریستارت

### ISSUE THREAD

**Issue by rasoolap** [salar403/vpn#1]
بعد ازدادن تغییرات نیاز هست ریستارت بشه ؟ بعد از ریبوت چی ؟ چطوری میتونم ریلانچ کنم با تغییرات جدید ؟

**Comment by salar403** [comment]
بعد تغییر کانفیگ باید کانتینر رو ریستارت کنین و نیاز به ریبوت کردن سرور نیست
با دستور docker-compose restart یا جفت دستور docker-compose down و  docker-compose up -d
